//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inluirme_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        public int id { get; set; }
        public Nullable<int> Encuesta_id { get; set; }
        public string descripcion { get; set; }
        public string respuesta { get; set; }
        public string descripcion_1 { get; set; }
        public string respuesta_1 { get; set; }
        public string descripcion_2 { get; set; }
        public string respuesta_2 { get; set; }
        public Nullable<int> Usuario_id { get; set; }
    
        public virtual Encuestas Encuestas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
