//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inluirme_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teaCapacitar
    {
        public int id { get; set; }
        public Nullable<int> idCapacitacion { get; set; }
        public Nullable<int> idUsuarios { get; set; }
    
        public virtual Capacitaciones Capacitaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
