//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inluirme_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Preguntas = new HashSet<Preguntas>();
            this.teaCapacitar = new HashSet<teaCapacitar>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage ="El campo nombre es requerido")]
        [Display(Name ="Ingrese su nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El campo apellido es requerido")]
        [Display(Name = "Ingrese su apellido")]
        public string apellido { get; set; }

        [Required(ErrorMessage = "El campo DNI es requerido")]
        [Display(Name = "Ingrese su D.N.I.")]
        [RegularExpression("[0-9]{8}", ErrorMessage = "Solo ingrese numero y debe tener 8 caracteres")]
        public Nullable<int> dni { get; set; }

        [Required(ErrorMessage = "El campo telefono es requerido")]
        [Display(Name = "Ingrese su Telefono")]
        public Nullable<int> telefono { get; set; }

        [Required(ErrorMessage = "El campo usuario es requerido")]
        [Display(Name = "Ingrese su usuario")]
        public string usuario { get; set; }

        [Required(ErrorMessage = "El campo contraseña es requerido")]
        [Display(Name = "Ingrese su contraseña")]
        [RegularExpression(@"((?=.*\d)(?=.*[a-zA-Z]).{8,50})", ErrorMessage ="Ingrese solo letras y numeros, minimo de 8 caracteres")]
        public string contra { get; set; }

        [Required(ErrorMessage = "El campo es requerido")]
        [Display(Name = "Discapacidad")]
        public string Discapacidad { get; set; }

        [Required(ErrorMessage = "El campo es requerido")]
        [Display(Name = "Ingrese su ultimo Empleo")]
        public string Empleo { get; set; }

        [Required(ErrorMessage = "El campo es requerido")]
        [Display(Name = "Capacitaciones y/o titulos")]
        public string Conocimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas> Preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teaCapacitar> teaCapacitar { get; set; }
    }
}
